language: cpp
sudo: required
dist: trusty
notifications:
  on_success: change
  on_failure: always
  on_start: false
cache:
  directories:
    - $HOME/boost

matrix:
  include:
    - os: linux
      env: USE_CC=gcc-4.9 USE_CXX=g++-4.9
      addons: &gcc49
        apt:
          packages:
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-4.9 gdb

    #- os: linux
    #  env: USE_CC=gcc-5 USE_CXX=g++-5
    #  addons: &gcc5
    #    apt:
    #      packages:
    #        - g++-5
    #        - libstdc++-5-dev
    #      sources:
    #        - ubuntu-toolchain-r-test
    #  install:
    #    - sudo apt-get update -qq
    #    - sudo apt-get install -qq g++-4.9

# boost.fiber does not compile with clang 3.5 atm
#    - os: linux
#      env: USE_CC=clang-3.5 USE_CXX=clang++-3.5
#      addons: &clang35
#        apt:
#          packages:
#            - clang-3.5
#          sources:
#            - llvm-toolchain-precise-3.5
#            - ubuntu-toolchain-r-test
#      install:
#        - sudo apt-get update -qq
#        - sudo apt-get install -qq g++-4.9

    #- os: linux
    #  env: USE_CC=clang-3.6 USE_CXX=clang++-3.6
    #  addons: &clang36
    #    apt:
    #      packages:
    #        - clang-3.6
    #      sources:
    #        - llvm-toolchain-precise-3.6
    #        - ubuntu-toolchain-r-test
    #  install:
    #    - sudo apt-get update -qq
    #    - sudo apt-get install -qq g++-4.9

before_script:
 - export CC=gcc-4.9; export CXX=g++-4.9
 - export BUILD_ROOT=$(pwd)
 - cd $HOME
 - if [ ! -d boost ]; then export BOOST_CLONE=1; git clone --recursive https://github.com/boostorg/boost.git; fi
 - pushd "boost"
 - if [ $BOOST_CLONE -ne 1 ]; then git pull; fi
 - pushd "libs"
 - if [ ! -d fiber ]; then git clone https://github.com/olk/boost-fiber.git fiber; else cd fiber; git pull; cd ..; fi
 - popd
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export GCC=$(which $CXX); fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "using gcc \x3a \x3a $GCC ;" > user-config.jam; cat user-config.jam; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bootstrap.sh --prefix=/usr/local/boost_head --with-libraries=fiber,context,thread,date_time,filesystem,system,program_options,test; fi
 - ./b2 -q -d0 --debug-configuration headers
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./b2 -q -d0 --user-config=user-config.jam cxxflags="-std=c++11 -fPIC" threading=multi link=static install; fi
 - popd
 - git clone https://github.com/tatsuhiro-t/nghttp2.git
 - pushd "nghttp2"
 - autoreconf -i && automake && autoconf
 - ./configure --with-boost=/usr/local/boost_head --enable-asio-lib
 - sudo make install
 - popd
 - curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz
 - pushd "lua-5.3.2"
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make linux CC="g++-4.9 -std=c++11"; fi
 - sudo make install
 - popd
 - cd $BUILD_ROOT
 - export CC=$USE_CC; export CXX=$USE_CXX

script:
  - mkdir build && cd build
  - cmake -DBOOST_ROOT=/usr/local/boost_head ..
  - make
  - ctest --output-on-failure
